// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createInventoryStmt, err = db.PrepareContext(ctx, createInventory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInventory: %w", err)
	}
	if q.createItemStmt, err = db.PrepareContext(ctx, createItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateItem: %w", err)
	}
	if q.deleteAuthorStmt, err = db.PrepareContext(ctx, deleteAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthor: %w", err)
	}
	if q.deleteInventoryStmt, err = db.PrepareContext(ctx, deleteInventory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInventory: %w", err)
	}
	if q.deleteItemStmt, err = db.PrepareContext(ctx, deleteItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteItem: %w", err)
	}
	if q.getAccountByIdStmt, err = db.PrepareContext(ctx, getAccountById); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountById: %w", err)
	}
	if q.getAccountByNameStmt, err = db.PrepareContext(ctx, getAccountByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByName: %w", err)
	}
	if q.getInventoryStmt, err = db.PrepareContext(ctx, getInventory); err != nil {
		return nil, fmt.Errorf("error preparing query GetInventory: %w", err)
	}
	if q.getItemStmt, err = db.PrepareContext(ctx, getItem); err != nil {
		return nil, fmt.Errorf("error preparing query GetItem: %w", err)
	}
	if q.listAccountsStmt, err = db.PrepareContext(ctx, listAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccounts: %w", err)
	}
	if q.listInventoriesStmt, err = db.PrepareContext(ctx, listInventories); err != nil {
		return nil, fmt.Errorf("error preparing query ListInventories: %w", err)
	}
	if q.listItemsStmt, err = db.PrepareContext(ctx, listItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListItems: %w", err)
	}
	if q.updateAccountPwdStmt, err = db.PrepareContext(ctx, updateAccountPwd); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountPwd: %w", err)
	}
	if q.updateItemStmt, err = db.PrepareContext(ctx, updateItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateItem: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createInventoryStmt != nil {
		if cerr := q.createInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInventoryStmt: %w", cerr)
		}
	}
	if q.createItemStmt != nil {
		if cerr := q.createItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createItemStmt: %w", cerr)
		}
	}
	if q.deleteAuthorStmt != nil {
		if cerr := q.deleteAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthorStmt: %w", cerr)
		}
	}
	if q.deleteInventoryStmt != nil {
		if cerr := q.deleteInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInventoryStmt: %w", cerr)
		}
	}
	if q.deleteItemStmt != nil {
		if cerr := q.deleteItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteItemStmt: %w", cerr)
		}
	}
	if q.getAccountByIdStmt != nil {
		if cerr := q.getAccountByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIdStmt: %w", cerr)
		}
	}
	if q.getAccountByNameStmt != nil {
		if cerr := q.getAccountByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByNameStmt: %w", cerr)
		}
	}
	if q.getInventoryStmt != nil {
		if cerr := q.getInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInventoryStmt: %w", cerr)
		}
	}
	if q.getItemStmt != nil {
		if cerr := q.getItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemStmt: %w", cerr)
		}
	}
	if q.listAccountsStmt != nil {
		if cerr := q.listAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccountsStmt: %w", cerr)
		}
	}
	if q.listInventoriesStmt != nil {
		if cerr := q.listInventoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listInventoriesStmt: %w", cerr)
		}
	}
	if q.listItemsStmt != nil {
		if cerr := q.listItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listItemsStmt: %w", cerr)
		}
	}
	if q.updateAccountPwdStmt != nil {
		if cerr := q.updateAccountPwdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountPwdStmt: %w", cerr)
		}
	}
	if q.updateItemStmt != nil {
		if cerr := q.updateItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateItemStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	createAccountStmt    *sql.Stmt
	createInventoryStmt  *sql.Stmt
	createItemStmt       *sql.Stmt
	deleteAuthorStmt     *sql.Stmt
	deleteInventoryStmt  *sql.Stmt
	deleteItemStmt       *sql.Stmt
	getAccountByIdStmt   *sql.Stmt
	getAccountByNameStmt *sql.Stmt
	getInventoryStmt     *sql.Stmt
	getItemStmt          *sql.Stmt
	listAccountsStmt     *sql.Stmt
	listInventoriesStmt  *sql.Stmt
	listItemsStmt        *sql.Stmt
	updateAccountPwdStmt *sql.Stmt
	updateItemStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		createAccountStmt:    q.createAccountStmt,
		createInventoryStmt:  q.createInventoryStmt,
		createItemStmt:       q.createItemStmt,
		deleteAuthorStmt:     q.deleteAuthorStmt,
		deleteInventoryStmt:  q.deleteInventoryStmt,
		deleteItemStmt:       q.deleteItemStmt,
		getAccountByIdStmt:   q.getAccountByIdStmt,
		getAccountByNameStmt: q.getAccountByNameStmt,
		getInventoryStmt:     q.getInventoryStmt,
		getItemStmt:          q.getItemStmt,
		listAccountsStmt:     q.listAccountsStmt,
		listInventoriesStmt:  q.listInventoriesStmt,
		listItemsStmt:        q.listItemsStmt,
		updateAccountPwdStmt: q.updateAccountPwdStmt,
		updateItemStmt:       q.updateItemStmt,
	}
}
