// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: inventories.sql

package db

import (
	"context"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (
  account_id,
  item_id
) VALUES (
  $1, $2
)
RETURNING id, account_id, item_id, create_time
`

type CreateInventoryParams struct {
	AccountID int64 `json:"accountId"`
	ItemID    int64 `json:"itemId"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.queryRow(ctx, q.createInventoryStmt, createInventory, arg.AccountID, arg.ItemID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ItemID,
		&i.CreateTime,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM inventories
WHERE id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteInventoryStmt, deleteInventory, id)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT id, account_id, item_id, create_time FROM inventories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInventory(ctx context.Context, id int64) (Inventory, error) {
	row := q.queryRow(ctx, q.getInventoryStmt, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ItemID,
		&i.CreateTime,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many
SELECT id, account_id, item_id, create_time FROM inventories
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListInventoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]Inventory, error) {
	rows, err := q.query(ctx, q.listInventoriesStmt, listInventories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ItemID,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
