// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Account struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	// 0-normal user 1-admin
	RoleType   int32     `json:"roleType"`
	CreateTime time.Time `json:"createTime"`
}

type Inventory struct {
	ID         int64     `json:"id"`
	AccountID  int64     `json:"accountId"`
	ItemID     int64     `json:"itemId"`
	CreateTime time.Time `json:"createTime"`
}

type Item struct {
	ID         int64     `json:"id"`
	ItemName   string    `json:"itemName"`
	ItemPrice  int32     `json:"itemPrice"`
	CreateTime time.Time `json:"createTime"`
	CreatorID  int64     `json:"creatorId"`
}
