apiVersion: v1
kind: ConfigMap 
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::029225022811:role/GitHub-CICD
      username: GitHub-CICD
      groups:
      - system:masters

  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::029225022811:user/zhangzhengrui
      username: zhangzhengrui
