apiVersion: v1
kind: ConfigMap 
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::029225022811:role/GitHub-CICD
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:masters

