apiVersion: v1
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::029225022811:role/AWSEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::029225022811:user/Github-CICD
      username: Github-CICD
      groups:
      - system:masters
