apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: red-pocket-game-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: red-pocket-game-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
