apiVersion: v1
kind: Service
metadata:
  name: red-pocket-game-service
spec:
  selector:
    app: red-pocket-game-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer